In [48]:
import torch
import torch.nn as nn
import torchvision
import numpy as np
import matplotlib.pyplot as plt

In [54]:
x=torch.randn(3,requires_grad=True)
print(x)
y=x+2
z=2*y**2
z=z.mean()
print(z)
z.backward()
x.grad

tensor([0.2040, 1.3387, 0.4408], requires_grad=True)
tensor(14.6412, grad_fn=<MeanBackward0>)


tensor([2.9387, 4.4515, 3.2544])

In [47]:
weights=torch.ones(4,requires_grad=True)
for epoch in range(3):
    model_output=(weights*3).sum()
    model_output.backward()
    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [53]:
weights=torch.ones(4,requires_grad=True)
optimizer=torch.optim.SGD([weights],lr=0.001)

In [52]:
x=torch.tensor(1.0)
y=torch.tensor(2.0)
w=torch.tensor(1.0,requires_grad=True)
y_hat=x*w
loss=(y-y_hat)**2
print(loss)
loss.backward()
print(w.grad)

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


In [49]:
x=np.array([1,2,2,6],dtype=np.float32)
y=x=np.array([1,3,2,8],dtype=np.float32)
w=0

# forward
def forward(x):
    return x*w

# loss
def loss(y,y_hat):
    return ((y-y_hat)**2).mean()
# gradient
# MSE = 1/n*(y-w*x)**2
# dJ/dw=2/n*(y-w*x)*x
def gradient(x,y,y_hat):
    return (-2*np.dot(x,y-y_hat)/len(x)).mean()

print(f"Prediction before training : f(5) = {forward(5):.3f}")

# training
# learning rate
lr=0.001

# iterations
# w = w-lr*dJ/dW
for epoch in range(300):
    # prediction
    y_hat=forward(x)
    # loss
    l = loss(y,y_hat)
    #dw
    dw = gradient(x,y,y_hat)
    w = w - lr * dw

    if epoch % 10 == 0:
        print(f'epoch {epoch} : w = {w:.3f} ,loss = {l:.8f}')

print(f"Prediction after training : f(5) = {forward(5):.3f}")

Prediction before training : f(5) = 0.000
epoch 0 : w = 0.039 ,loss = 19.50000000
epoch 10 : w = 0.354 ,loss = 8.80039787
epoch 20 : w = 0.566 ,loss = 3.97164249
epoch 30 : w = 0.709 ,loss = 1.79241216
epoch 40 : w = 0.804 ,loss = 0.80892015
epoch 50 : w = 0.869 ,loss = 0.36506754
epoch 60 : w = 0.912 ,loss = 0.16475582
epoch 70 : w = 0.941 ,loss = 0.07435471
epoch 80 : w = 0.960 ,loss = 0.03355645
epoch 90 : w = 0.973 ,loss = 0.01514416
epoch 100 : w = 0.982 ,loss = 0.00683461
epoch 110 : w = 0.988 ,loss = 0.00308444
epoch 120 : w = 0.992 ,loss = 0.00139200
epoch 130 : w = 0.995 ,loss = 0.00062822
epoch 140 : w = 0.996 ,loss = 0.00028351
epoch 150 : w = 0.998 ,loss = 0.00012795
epoch 160 : w = 0.998 ,loss = 0.00005774
epoch 170 : w = 0.999 ,loss = 0.00002606
epoch 180 : w = 0.999 ,loss = 0.00001176
epoch 190 : w = 0.999 ,loss = 0.00000531
epoch 200 : w = 1.000 ,loss = 0.00000240
epoch 210 : w = 1.000 ,loss = 0.00000108
epoch 220 : w = 1.000 ,loss = 0.00000049
epoch 230 : w = 1.000 ,lo

In [50]:
x = torch.tensor([1,2,3,4],dtype=torch.float32)
y = torch.tensor([3,2,1,6],dtype=torch.float32)
w = torch.tensor(0.,dtype=torch.float32,requires_grad=True)

# forward 
def forward(x):
    return w*x

print(f'Before training f(5) : {forward(5):.3f}')

# training
learning_rate = 0.001

loss = nn.MSELoss()
optimizer = torch.optim.SGD([w],lr=learning_rate)

for epoch in range(1000):
    # forward pass
    y_predict=forward(x)
    # loss
    l=loss(y,y_predict)
    l.backward()
    with torch.no_grad():
        w -= learning_rate * w.grad
    w.grad.zero_()
    if epoch % 10 == 0:
        print(f'epoch {epoch} : w = {w:.3f} , loss = {l:.8f}')

print(f'After training f(5) : {forward(5):.3f}')



Before training f(5) : 0.000
epoch 0 : w = 0.017 , loss = 12.50000000
epoch 10 : w = 0.174 , loss = 9.98701477
epoch 20 : w = 0.308 , loss = 8.12957478
epoch 30 : w = 0.424 , loss = 6.75667477
epoch 40 : w = 0.523 , loss = 5.74191332
epoch 50 : w = 0.609 , loss = 4.99186611
epoch 60 : w = 0.683 , loss = 4.43747902
epoch 70 : w = 0.746 , loss = 4.02771091
epoch 80 : w = 0.800 , loss = 3.72483635
epoch 90 : w = 0.847 , loss = 3.50097132
epoch 100 : w = 0.887 , loss = 3.33550453
epoch 110 : w = 0.922 , loss = 3.21320200
epoch 120 : w = 0.951 , loss = 3.12280369
epoch 130 : w = 0.977 , loss = 3.05598664
epoch 140 : w = 0.999 , loss = 3.00659990
epoch 150 : w = 1.018 , loss = 2.97009659
epoch 160 : w = 1.034 , loss = 2.94311500
epoch 170 : w = 1.048 , loss = 2.92317247
epoch 180 : w = 1.060 , loss = 2.90843201
epoch 190 : w = 1.070 , loss = 2.89753675
epoch 200 : w = 1.079 , loss = 2.88948417
epoch 210 : w = 1.087 , loss = 2.88353181
epoch 220 : w = 1.093 , loss = 2.87913227
epoch 230 : w =

epoch 900 : w = 1.133 , loss = 2.86666656
epoch 910 : w = 1.133 , loss = 2.86666656
epoch 920 : w = 1.133 , loss = 2.86666656
epoch 930 : w = 1.133 , loss = 2.86666656
epoch 940 : w = 1.133 , loss = 2.86666656
epoch 950 : w = 1.133 , loss = 2.86666656
epoch 960 : w = 1.133 , loss = 2.86666656
epoch 970 : w = 1.133 , loss = 2.86666656
epoch 980 : w = 1.133 , loss = 2.86666656
epoch 990 : w = 1.133 , loss = 2.86666656
epoch 1000 : w = 1.133 , loss = 2.86666656
epoch 1010 : w = 1.133 , loss = 2.86666656
epoch 1020 : w = 1.133 , loss = 2.86666656
epoch 1030 : w = 1.133 , loss = 2.86666656
epoch 1040 : w = 1.133 , loss = 2.86666656
epoch 1050 : w = 1.133 , loss = 2.86666656
epoch 1060 : w = 1.133 , loss = 2.86666656
epoch 1070 : w = 1.133 , loss = 2.86666656
epoch 1080 : w = 1.133 , loss = 2.86666656
epoch 1090 : w = 1.133 , loss = 2.86666656
epoch 1100 : w = 1.133 , loss = 2.86666656
epoch 1110 : w = 1.133 , loss = 2.86666656
epoch 1120 : w = 1.133 , loss = 2.86666656
epoch 1130 : w = 1.13

In [51]:
x = torch.tensor([1,2,3,4],dtype=torch.float32)
y = torch.tensor([3,2,1,5],dtype=torch.float32)
w = torch.tensor(0.,dtype=torch.float32,requires_grad=True)

# forward 
def forward(x):
    return w*x

print(f'Before training f(5) : {forward(5):.3f}')

# training
learning_rate = 0.001

loss = nn.MSELoss()
optimizer = torch.optim.SGD([w],lr=learning_rate)

for epoch in range(1000):
    # forward pass
    y_predict=forward(x)
    # loss
    l=loss(y,y_predict)
    l.backward()
    optimizer.step()
    optimizer.zero_grad()
    if epoch % 10 == 0:
        print(f'epoch {epoch} : w = {w:.3f} , loss = {l:.8f}')

print(f'After training f(5) : {forward(5):.3f}')



Before training f(5) : 0.000
epoch 0 : w = 0.015 , loss = 9.75000000
epoch 10 : w = 0.153 , loss = 7.79352379
epoch 20 : w = 0.272 , loss = 6.34742069
epoch 30 : w = 0.374 , loss = 5.27855206
epoch 40 : w = 0.462 , loss = 4.48851299
epoch 50 : w = 0.537 , loss = 3.90456629
epoch 60 : w = 0.602 , loss = 3.47295046
epoch 70 : w = 0.658 , loss = 3.15392733
epoch 80 : w = 0.706 , loss = 2.91812611
epoch 90 : w = 0.747 , loss = 2.74383640
epoch 100 : w = 0.783 , loss = 2.61501241
epoch 110 : w = 0.813 , loss = 2.51979423
epoch 120 : w = 0.839 , loss = 2.44941473
epoch 130 : w = 0.862 , loss = 2.39739442
epoch 140 : w = 0.881 , loss = 2.35894418
epoch 150 : w = 0.898 , loss = 2.33052444
epoch 160 : w = 0.912 , loss = 2.30951858
epoch 170 : w = 0.925 , loss = 2.29399252
epoch 180 : w = 0.935 , loss = 2.28251672
epoch 190 : w = 0.944 , loss = 2.27403402
epoch 200 : w = 0.952 , loss = 2.26776457
epoch 210 : w = 0.959 , loss = 2.26313019
epoch 220 : w = 0.965 , loss = 2.25970531
epoch 230 : w = 