In [17]:
import torch
import torch.nn as nn
import torchvision
import numpy as np
import matplotlib.pyplot as plt

In [18]:
x=torch.randn(3,requires_grad=True)
print(x)
y=x+2
z=2*y**2
z=z.mean()
print(z)
z.backward()
x.grad

tensor([-0.2280,  0.7277, -0.6973], requires_grad=True)
tensor(8.1849, grad_fn=<MeanBackward0>)


tensor([2.3627, 3.6369, 1.7369])

In [19]:
weights=torch.ones(4,requires_grad=True)
for epoch in range(3):
    model_output=(weights*3).sum()
    model_output.backward()
    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [20]:
weights=torch.ones(4,requires_grad=True)
optimizer=torch.optim.SGD([weights],lr=0.001)

In [21]:
x=torch.tensor(1.0)
y=torch.tensor(2.0)
w=torch.tensor(1.0,requires_grad=True)
y_hat=x*w
loss=(y-y_hat)**2
print(loss)
loss.backward()
print(w.grad)

tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


In [22]:
x=np.array([1,2,2,6],dtype=np.float32)
y=x=np.array([1,3,2,8],dtype=np.float32)
w=0

# forward
def forward(x):
    return x*w

# loss
def loss(y,y_hat):
    return ((y-y_hat)**2).mean()
# gradient
# MSE = 1/n*(y-w*x)**2
# dJ/dw=2/n*(y-w*x)*x
def gradient(x,y,y_hat):
    return (-2*np.dot(x,y-y_hat)/len(x)).mean()

print(f"Prediction before training : f(5) = {forward(5):.3f}")

# training
# learning rate
lr=0.001

# iterations
# w = w-lr*dJ/dW
for epoch in range(300):
    # prediction
    y_hat=forward(x)
    # loss
    l = loss(y,y_hat)
    #dw
    dw = gradient(x,y,y_hat)
    w = w - lr * dw

    if epoch % 50 == 0:
        print(f'epoch {epoch} : w = {w:.3f} ,loss = {l:.8f}')

print(f"Prediction after training : f(5) = {forward(5):.3f}")

Prediction before training : f(5) = 0.000
epoch 0 : w = 0.039 ,loss = 19.50000000
epoch 50 : w = 0.869 ,loss = 0.36506754
epoch 100 : w = 0.982 ,loss = 0.00683461
epoch 150 : w = 0.998 ,loss = 0.00012795
epoch 200 : w = 1.000 ,loss = 0.00000240
epoch 250 : w = 1.000 ,loss = 0.00000004
Prediction after training : f(5) = 5.000


In [23]:
x = torch.tensor([1,2,3,4],dtype=torch.float32)
y = torch.tensor([3,2,1,6],dtype=torch.float32)
w = torch.tensor(0.,dtype=torch.float32,requires_grad=True)

# forward 
def forward(x):
    return w*x

print(f'Before training f(5) : {forward(5):.3f}')

# training
learning_rate = 0.001

loss = nn.MSELoss()
optimizer = torch.optim.SGD([w],lr=learning_rate)

for epoch in range(1000):
    # forward pass
    y_predict=forward(x)
    # loss
    l=loss(y,y_predict)
    l.backward()
    with torch.no_grad():
        w -= learning_rate * w.grad
    w.grad.zero_()
    if epoch % 100 == 0:
        print(f'epoch {epoch} : w = {w:.3f} , loss = {l:.8f}')

print(f'After training f(5) : {forward(5):.3f}')



Before training f(5) : 0.000
epoch 0 : w = 0.017 , loss = 12.50000000
epoch 100 : w = 0.887 , loss = 3.33550453
epoch 200 : w = 1.079 , loss = 2.88948417
epoch 300 : w = 1.121 , loss = 2.86777711


epoch 400 : w = 1.131 , loss = 2.86672068
epoch 500 : w = 1.133 , loss = 2.86666918
epoch 600 : w = 1.133 , loss = 2.86666679
epoch 700 : w = 1.133 , loss = 2.86666632
epoch 800 : w = 1.133 , loss = 2.86666679
epoch 900 : w = 1.133 , loss = 2.86666656
After training f(5) : 5.667


In [24]:
x = torch.tensor([1,2,3,4],dtype=torch.float32)
y = torch.tensor([3,2,1,5],dtype=torch.float32)
w = torch.tensor(0.,dtype=torch.float32,requires_grad=True)

# forward 
def forward(x):
    return w*x

print(f'Before training f(5) : {forward(5):.3f}')

# training
learning_rate = 0.001

loss = nn.MSELoss()
optimizer = torch.optim.SGD([w],lr=learning_rate)

for epoch in range(1000):
    # forward pass
    y_predict=forward(x)
    # loss
    l=loss(y,y_predict)
    l.backward()
    optimizer.step()
    optimizer.zero_grad()
    if epoch % 100 == 0:
        print(f'epoch {epoch} : w = {w:.3f} , loss = {l:.8f}')

print(f'After training f(5) : {forward(5):.3f}')



Before training f(5) : 0.000
epoch 0 : w = 0.015 , loss = 9.75000000
epoch 100 : w = 0.783 , loss = 2.61501241
epoch 200 : w = 0.952 , loss = 2.26776457
epoch 300 : w = 0.989 , loss = 2.25086451
epoch 400 : w = 0.998 , loss = 2.25004220
epoch 500 : w = 0.999 , loss = 2.25000215
epoch 600 : w = 1.000 , loss = 2.25000000
epoch 700 : w = 1.000 , loss = 2.25000000
epoch 800 : w = 1.000 , loss = 2.25000000
epoch 900 : w = 1.000 , loss = 2.25000000
After training f(5) : 5.000
